name: Build e Push da Imagem Bootc

on:
  schedule:
    # 07:00 UTC representa 04:00 da manhã no horário de Brasília (UTC-3)
    - cron: '0 7 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch: # Permite rodar manualmente a qualquer momento

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extrair metadados (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short
            latest

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Otimização de cache para builds rápidos
          cache-from: type=gha
          cache-to: type=gha,mode=max

- name: Notificar Sucesso no Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Imagem Bootc atualizada com sucesso!
            O sistema já está pronto para o upgrade.
            Build: ${{ github.sha }}

      - name: Notificar Falha no Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Erro no Build das 04:00!
            Verifique os logs no GitHub: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
